proj:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: ":memory:"
      schema: main               # REQUIRED by dbt
      schemas_and_paths:         # REQUIRED by dbt 1.11+
        main: "models"        # maps the "models" folder to "main" schema